from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.IndexView, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('register/', views.RegisterView, name='register'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('forgot-password/', views.ForgotPassword, name='forgot-password'),
    path('password-reset-sent/<str:reset_id>/', views.PasswordResetSent, name='password-reset-sent'),
    path('reset-password/<str:reset_id>/', views.ResetPassword, name='reset-password'),
    path('admin-login/', views.AdminLoginView, name='admin-login'),
    path('admin-dashboard/', views.AdminDashboardView, name='admin_dashboard'),  # Admin dashboard
    path('admin-logout/', views.AdminLogoutView, name='admin-logout'),
    path('redirect/', views.CustomRedirectView, name='custom_redirect'),
    path('admin-register/', views.AdminRegisterView, name='admin-register'),
    path('admin-forgot-password/', views.AdminForgotPasswordView, name='admin-forgot-password'),
    path('admin-password-reset-sent/<str:reset_id>/', views.AdminPasswordResetSent, name='admin-password-reset-sent'),
    path('admin-reset-password/<str:reset_id>/', views.AdminResetPassword, name='admin-reset-password'),
    path('dashboard/', views.DashboardView, name='dashboard'),
    path('inventory/', views.InventoryView, name='inventory'),
    path('inventory/edit/<int:pk>/', views.InventoryView, name='edit-inventory'),
    path('payment/', views.PaymentView, name='payment'),
    path('order/', views.OrderView, name='order'),
    path('pay/<int:order_id>/', views.payment_page, name='payment_page'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('approve-order/<int:order_id>/', views.AdminApproveOrderView, name='admin_approve_order'),
    path('order/pending/', views.order_pending, name='order_pending'),
    path('agent-signup/', views.agent_signup, name='agent_signup'),
    path('agent-login/', views.agent_login, name='agent_login'),
    path('agent-dashboard/', views.agent_dashboard, name='agent_dashboard'),
    path('start-delivery/<int:order_id>/', views.start_delivery, name='start_delivery'),
    path('mark-delivered/<int:order_id>/', views.mark_delivered, name='mark_delivered'),
]
