# Generated by Django 5.2 on 2025-05-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
