# Generated by Django 5.2 on 2025-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
