# Generated by Django 5.2 on 2025-06-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_order_user_payment_order_alter_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_pump',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
