# Generated by Django 5.2 on 2025-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_order_selected_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_pump',
            field=models.CharField(max_length=100),
        ),
    ]
