# Generated by Django 5.2.4 on 2025-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_order_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
